### ISSUE TITLE
AutomaThemely fails to start when ran from its desktop file

### ISSUE THREAD

**Issue by logix2** [C2N14/AutomaThemely#2]
Running AutomaThemely from its desktop file (so from its menu entry), the application fails to start. Looking at the automathemely.desktop file, the main entry is ``Exec=automathemely`` and this doesn't seem to run the GUI (it should have ``automathemely --manage`` for the main entry exec to actually open the GUI).

**Comment by C2N14** [comment]
This is actually intended behavior as if the scheduler fails to start you can click the icon to temporarily fix the issue, this came in handy specially before because crontabs weren't exactly super reliable. I believe in GNOME you can always right click the icon and select _Manage settings_.

Although I may consider changing it in a future version because the scheduler is safer and more reliable than ever.

**Comment by logix2** [comment]
But this is the only application for which the GUI doesn't start when you click the icon. Nobody expects the GUI not to run.
